# gcloud builds submit --config=./patcher/cloudbuild.yaml . --substitutions=_VERSION=0.8.0
steps:
- name: maven:3.6.2-jdk-8-slim
  entrypoint: 'mvn'
  args: ['package','-f','./patcher/pom.xml']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/patcher:${_VERSION}', './patcher/']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/patcher:latest', './patcher/']
images: ['gcr.io/$PROJECT_ID/patcher']
substitutions:
    _VERSION: 0.8.0